//
//  Character.swift
//  OnePiece
//
//  Created by Freddy A. on 7/10/21.
//

import Foundation

class Character{
    var mainCharacterSample: eCharacters{
        [
            eCharacter(image: "mgCharacterLuffy",
                       name: "Monkey D. Luffy",
                       position: "Capitán",
                       type: "Pirata",
                       episodeInit: 1,
                       bigImage: "mgCharacterLuffyHeader",
                       information: "Monkey D. Luffy (モンキー・Ｄ・ルフィ), más conocido como Luffy (Sombrero de Paja) (麦わらのルフィ), es el protagonista principal de la serie de manga y anime One Piece. Comió una fruta del diablo de tipo paramecia llamada fruta Gomu Gomu, que le convirtió en un hombre de goma. Además de esto, posee varias habilidades que le hacen ser un pirata más que especial; un gran ejemplo de ello es la capacidad de usar el haoshoku haki ―que sólo lo posee una persona dentro de un millón― y poseer también los otros dos tipos de haki."
            ),
            eCharacter(image: "mgCharacterZoro",
                       name: "Roronoa Zoro",
                       position: "Combatiente",
                       type: "Pirata",
                       episodeInit: 3,
                       bigImage: "mgCharacterZoroHeader",
                       information: "Roronoa Zoro (ロロノア・ ゾロ), conocido como El Cazador de Piratas (海賊狩り), es el combatiente de los Piratas de Sombrero de Paja, y uno de sus dos espadachines, así como un antiguo cazarrecompensas."
            ),
            eCharacter(image: "mgCharacterNami",
                       name: "Nami",
                       position: "Navegante",
                       type: "Pirata",
                       episodeInit: 8,
                       bigImage: "mgCharacterNamiHeader",
                       information: "Nami (ナミ), apodada Gata Ladrona (泥棒猫), es una pirata y la navegante de los Piratas del Sombrero de Paja, así como una de las protagonistas principales de la serie. Es el tercer miembro de la tripulación y la segunda en unirse, haciéndolo oficialmente durante el arco de Arlong Park."),
            eCharacter(image: "mgCharacterUsopp",
                       name: "Usopp",
                       position: "Francotirador",
                       type: "Pirata",
                       episodeInit: 23,
                       bigImage: "mgCharacterUsoppHeader",
                       information: "Usopp (ウソップ) es el francotirador de los Piratas de Sombrero de Paja. Es el cuarto miembro de la tripulación y el tercero en unirse oficialmente. A pesar de abandonar la banda en el arco de Water 7, se volvió a unir en el arco del regreso a Water 7."),
            eCharacter(image: "mgCharacterSanji",
                       name: "Sanji",
                       position: "Cocinero",
                       type: "Pirata",
                       episodeInit: 43,
                       bigImage: "mgCharacterSanjiHeader",
                       information: "Sanji (サンジ), conocido como Pierna Negra (黒脚) y nacido como Vinsmoke Sanji (ヴィンスモーク・サンジ), es el cocinero de los Piratas de Sombrero de Paja, el tercer hijo de la familia Vinsmoke y uno de los protagonistas principales del manga y anime de One Piece. Es el quinto miembro de la tripulación, y el cuarto en unirse. Al haber nacido en el North Blue, fue el primer tripulante en no ser originario del East Blue. Forma parte del «Trío Monstruoso» junto a Luffy y Roronoa Zoro; y, como tal, es uno de los combatientes más fuertes de la tripulación."),
            eCharacter(image: "mgCharacterChopper",
                       name: "Tony Tony Chopper",
                       position: "Médico",
                       type: "Pirata",
                       episodeInit: 134,
                       bigImage: "mgCharacterChopperHeader",
                       information: "Tony Tony Chopper (トニートニー・チョッパー) es el médico de los Piratas de Sombrero de Paja. Es un reno que comió la fruta Hito Hito de la isla de Drum. Él es el sexto miembro de la tripulación y el quinto en unirse a ella."),
            eCharacter(image: "mgCharacterRobin",
                       name: "Nico Robin",
                       position: "Arqueóloga",
                       type: "Pirata",
                       episodeInit: 114,
                       bigImage: "mgCharacterRobinHeader",
                       information: "Nico Robin (ニコ・ロビン), también conocida por sus epítetos: Niña Demonio (悪魔の子) y La Luz de la Revolución (革命の灯 es la arqueóloga de los Piratas de Sombrero de Paja. Es el séptimo miembro de la tripulación y el sexto en unirse, haciéndolo al final del arco de Arabasta. Dejó temporalmente a la tripulación durante el arco de Water 7, pero se reincorporó durante el arco de Enies Lobby."),
            eCharacter(image: "mgCharacterFranky",
                       name: "Franky",
                       position: "Carpintero Naval",
                       type: "Pirata",
                       episodeInit: 329,
                       bigImage: "mgCharacterFrankyHeader",
                       information: "Franky (フランキー) cuyo verdadero nombre es Cutty Flam (カティ・フラム), es un cyborg (mitad androide, mitad humano) quien era el líder de la Familia Franky, un grupo de desmanteladores de Water 7 que hacen a la vez el trabajo de cazadores de recompensas."),
            eCharacter(image: "mgCharacterBrook",
                       name: "Brook",
                       position: "Músico",
                       type: "Pirata",
                       episodeInit: 442,
                       bigImage: "mgCharacterBrookHeader",
                       information: "Brook (ブルック) es el músico de los Piratas de Sombrero de Paja, y uno de sus dos espadachines. Es un esqueleto viviente que encontraron en un barco fantasma solo, porque habían envenenado a toda su anterior tripulación. Es el consumidor de una fruta del diablo, más concretamente la fruta Yomi Yomi, y ahora es un no-muerto traído de vuelta al mundo de los vivos como un pseudo-inmortal, debido a sus poderes."),
            eCharacter(image: "mgCharacterJinbe",
                       name: "Jinbē",
                       position: "Timonel",
                       type: "Pirata",
                       episodeInit: 528,
                       bigImage: "mgCharacterJinbeHeader",
                       information: "Jinbe el Caballero del Mar (海侠のジンベエ) es el timonel de los Piratas de Sombrero de Paja, siendo el décimo miembro de la banda y el noveno en unirse. Es un gyojin tiburón ballena, que sirvió como antiguo capitán de los Piratas del Sol[10] y como miembro de los Siete Guerreros del Mar."),
            eCharacter(image: "mgCharacterVivi",
                       name: "Nefertari Vivi",
                       position: "Capitan",
                       type: "Pirata",
                       episodeInit: 103,
                       bigImage: "mgCharacterViviHeader",
                       information: "Nefertari Vivi (ネフェルタリ・ビビ) es la princesa heredera del reino de Arabasta, ya que es hija de Cobra. Se infiltró en Baroque Works tomando la identidad de Miss Wednesday (ミス・ウェンズデー) junto a Igaram, quien se llamó Mr. 8, dentro de la organización para descubrir la identidad del misterioso líder Mr. 0 y su propósito."),
        ]
    }
    
    var badCharacterSample: eCharacters{
        [
            eCharacter(image: "mgCharacterRoger",
                       name: "Gold Roger",
                       position: "Capitán",
                       type: "Rey de los Piratas",
                       episodeInit: 0,
                       bigImage: "mgCharacterRogerHeader",
                       information: "Gol D. Roger (ゴール・D・ロジャー) mejor conocido como Gold Roger (ゴールド・ロジャー), fue el capitán de los Piratas de Roger, siendo a su vez conocido como el Rey de los Piratas (海賊王), título que le fue concedido tras conquistar todo el Grand Line, y al ser el dueño del legendario tesoro conocido como «One Piece» tras ser el primero junto a su tripulación en llegar a Laugh Tale en los últimos ochocientos años."),
            eCharacter(image: "mgCharacterShaks",
                       name: "Shanks",
                       position: "Capitán",
                       type: "Emperador",
                       episodeInit: 0,
                       bigImage: "mgCharacterShaksHeader",
                       information: "Shanks el Pelirrojo (赤髪のシャンクス), es el capitán de los Piratas del Pelirrojo y uno de los Cuatro Emperadores que gobiernan el Nuevo Mundo. Fue, además, un miembro de la legendaria tripulación de Gol D. Roger, siendo la única banda que logró conquistar con éxito todo Grand Line."),
            eCharacter(image: "mgCharacterBigMama",
                       name: "Charlotte Linlin",
                       position: "Capitán",
                       type: "Emperador",
                       episodeInit: 0,
                       bigImage: "mgCharacterBigMamaHeader",
                       information: "Charlotte Linlin (シャー ロット リンリン), más conocida como Big Mom (マム ビッグ Biggu Mamu?, lit. «Gran Mamá»), es la capitana de los Piratas de Big Mom, matriarca de la familia Charlotte, reina de Totto Land y uno de los Cuatro Emperadores que gobiernan los mares del Nuevo Mundo. Al igual que varios piratas del pasado de renombre, fue miembro de los Piratas de Rocks."),
            eCharacter(image: "mgCharacterKaido",
                       name: "Kaido",
                       position: "Capitán",
                       type: "Emperador",
                       episodeInit: 0,
                       bigImage: "mgCharacterKaidoHeader",
                       information: "Kaido de las Bestias (百獣のカイドウ), conocido también como la Criatura más Poderosa (最強の生物 Saikyō no Seibutsu?), es el gobernador general de los Piratas de las Bestias y uno de los Cuatro Emperadores que gobiernan los mares del Nuevo Mundo. Fue además un aprendiz de los legendarios Piratas de Rocks durante su juventud. Fue el tercer emperador en ser mencionado y el último en hacer aparición. Actualmente, él y su tripulación se encuentran ocupando el País de Wano."),
            eCharacter(image: "mgCharacterBarbaNegra",
                       name: "Marshall D. Teach",
                       position: "Capitán",
                       type: "Emperador",
                       episodeInit: 0,
                       bigImage: "mgCharacterBarbaNegraHeader",
                       information: "Marshall D. Teach (マーシャル・D・ティーチ), más conocido como Barbanegra (黒ひげ Kurohige?) es el almirante de los Piratas de Barbanegra y uno de los Cuatro Emperadores que gobiernan los mares del Nuevo Mundo, estatus que consolidó tras su victoria en la Batalla de la Venganza frente a los Piratas de Barbablanca. Actualmente él y su banda se encuentran ocupando Hachinosu."),
            eCharacter(image: "mgCharacterBarbaBlanca",
                       name: "Edward Newgate†",
                       position: "Capitán",
                       type: "Emperador",
                       episodeInit: 0,
                       bigImage: "mgCharacterBarbaBlancaHeader",
                       information: "Edward Newgate (エドワード・二ューゲート), más conocido como Barbablanca (白ひげ Shirohige?), fue el capitán de los Piratas de Barbablanca y el histórico rival de Gol D. Roger. Tras la muerte de este, fue conocido como el Hombre más cercano al One Piece (ワンピースに最も近い男 Wan Pīsu ni mottomo chikai otoko), además de ser reconocido como el Hombre más fuerte del Mundo (世界最強の男 Sekai saikyō no otoko."),
            eCharacter(image: "mgCharacterDoflamingo",
                       name: "Donquixote Doflamingo",
                       position: "Gerrero del Mar",
                       type: "Pirata",
                       episodeInit: 0,
                       bigImage: "mgCharacterDoflamingoHeader",
                       information: "Donquixote Doflamingo (ドンキホーテ・ドフラミンゴ), más conocido por sus epítetos: Yaksha Celestial (天夜叉) en el mundo de la piratería, Joker (ジョーカー Jōkā?) en el Inframundo; y el Carisma del Mal (悪のカリスマ); es un antiguo Guerrero del Mar, que reinaba en Dressrosa, y un anterior Noble Mundial. Hijo de Donquixote Homing y hermano mayor de Donquixote Rosinante, es un integrante de la Familia Donquixote, la familia real regente hace ochocientos años en el país. Doflamingo es el capitán de los Piratas Donquixote y el Bróker más influyente de los Bajos Fondos detrás del alias de Joker."),
            eCharacter(image: "mgCharacterArlong",
                       name: "Arlong",
                       position: "Capitán",
                       type: "Pirata",
                       episodeInit: 0,
                       bigImage: "mgCharacterArlongHeader",
                       information: "Arlong la Sierra (ノコギリのアーロン) es un gyojin tiburón sierra capitán de los Piratas de Arlong y antiguo miembro de los Piratas del Sol. Es el principal antagonista del arco de Arlong Park."),
            eCharacter(image: "mgCharacterSakazuki",
                       name: "Sakazuki",
                       position: "Almirante de la Flota",
                       type: "Marine",
                       episodeInit: 0,
                       bigImage: "mgCharacterSakazukiHeader",
                       information: "Sakazuki (サカズキ), más conocido como «Akainu» (赤犬 Akainu) es el almirante de la flota del cuartel general de la Marine. Hace dos años era uno de los tres almirantes que participaron en la guerra de Marineford, en la cual acabó con la vida de Portgas D. Ace."),
            eCharacter(image: "mgCharacterIssho",
                       name: "Fujitora",
                       position: "Almirante",
                       type: "Marine",
                       episodeInit: 0,
                       bigImage: "mgCharacterIsshoHeader",
                       information: "Issho es un hombre con un temperamento modesto, gentil y tranquilo, y destaca por su afición a los juegos de azar. Su visión de la justicia difiere mucho del postulado absolutista defendido por convención por la Marine y el Gobierno y parece basarse en aquel viejo ideal del s. XVI de la «justicia ciega» (盲目の正義), que representa una justicia idealizada e imparcial, y cuya aplicación se efectúa sin atender a criterios de riqueza, poder, influencia u otros factores; es decir, una justicia centrada en los hechos y no en los individuos que dicta, en definitiva, que la ley debe ser igual para todos."),
            eCharacter(image: "mgCharacterKirazu",
                       name: "Kizaru",
                       position: "Almirante",
                       type: "Marine",
                       episodeInit: 0,
                       bigImage: "mgCharacterKirazuHeader",
                       information: "Borsalino (ボルサリーノ), más conocido como Kizaru (黄猿 «Mono Amarillo») es uno de los tres almirantes del cuartel general de la Marine. Actuó como antagonista secundario en el arco del Archipiélago Sabaody, en el de Marineford y en Film Z."),
        ]
    }
}


